[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Remove the invalid timeout setting or use correct syntax
  node_bundler = "esbuild"
  
  # If you need timeout configuration, use this format:
  [functions.settings]
    timeout = 10 # seconds